'''

Docker is open platform for developing and shipping applications.


Docker is an open-source platform that lets us package applications and their dependencies into lightweight, portable units called containers, ensuring they
run consistently across different environments.



* DockerFile contains all dependency versions and requirements to run the application.

* Image is generated by DockerFile in the repo.

* If we run the above image on host system then it becomes a container.

* with the help of single image, we can create multiple containers.

----------


Dockerfile contains the logic of installing requirements, copying the backend code, what hosts can hit this backend code.



docker build packs the whole backend code, installs requirements and freezes everything into an image.


docker run creates a container which starts the server (providing RAM, CPU etc)


'''