insert into p1pcp_system.table_permissions.required_permissions values
('i1int_prospect','client_works','','i1int','us','prospect_aws_db_i1int_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('i1int_prospect','client_works','','i1int','us','i1int_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('i1pros_prospect','client_works','','i1pros','us','prospect_aws_db_i1pros_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('i1pros_prospect','client_works','','i1pros','us','i1pros_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1abacus_prospect','client_works','','p1abacus','us','prospect_aws_db_p1abacus_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1abacus_prospect','client_works','','p1abacus','us','p1abacus_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1abi_prospect','client_works','','p1abi','us','prospect_aws_db_p1abi_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1abi_prospect','client_works','','p1abi','us','p1abi_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1aitso_prospect','client_works','','p1aitso','us','prospect_aws_db_p1aitso_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1aitso_prospect','client_works','','p1aitso','us','p1aitso_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1auto_prospect','client_works','','p1auto','us','prospect_aws_db_p1auto_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1auto_prospect','client_works','','p1auto','us','p1auto_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1blue_prospect','client_works','','p1blue','us','prospect_aws_db_p1blue_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1blue_prospect','client_works','','p1blue','us','p1blue_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1boa_prospect','client_works','','p1boa','us','prospect_aws_db_p1boa_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1boa_prospect','client_works','','p1boa','us','p1boa_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1clax_prospect','client_works','','p1clax','us','prospect_aws_db_p1clax_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1clax_prospect','client_works','','p1clax','us','p1clax_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1clnt_prospect','client_works','','p1clnt','us','prospect_aws_db_p1clnt_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1clnt_prospect','client_works','','p1clnt','us','p1clnt_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1clrm_prospect','client_works','','p1clrm','us','prospect_aws_db_p1clrm_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1clrm_prospect','client_works','','p1clrm','us','p1clrm_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1colx_prospect','client_works','','p1colx','us','prospect_aws_db_p1colx_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1colx_prospect','client_works','','p1colx','us','p1colx_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1comcast_prospect','client_works','','p1comcast','us','prospect_aws_db_p1comcast_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1comcast_prospect','client_works','','p1comcast','us','p1comcast_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1cpb_prospect','client_works','','p1cpb','us','prospect_aws_db_p1cpb_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1cpb_prospect','client_works','','p1cpb','us','p1cpb_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1crmx_prospect','client_works','','p1crmx','us','prospect_aws_db_p1crmx_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1crmx_prospect','client_works','','p1crmx','us','p1crmx_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1dasa_prospect','client_works','','p1dasa','us','prospect_aws_db_p1dasa_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1dasa_prospect','client_works','','p1dasa','us','p1dasa_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1demo_prospect','client_works','','p1demo','us','prospect_aws_db_p1demo_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1demo_prospect','client_works','','p1demo','us','p1demo_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1digitas_prospect','client_works','','p1digitas','us','prospect_aws_db_p1digitas_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1digitas_prospect','client_works','','p1digitas','us','p1digitas_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1directv_prospect','client_works','','p1directv','us','prospect_aws_db_p1directv_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1directv_prospect','client_works','','p1directv','us','p1directv_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1dsnx_prospect','client_works','','p1dsnx','us','prospect_aws_db_p1dsnx_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1dsnx_prospect','client_works','','p1dsnx','us','p1dsnx_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1dsnx_temp_prospect','client_works','','p1dsnx_temp','us','prospect_aws_db_p1dsnx_temp_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1dsnx_temp_prospect','client_works','','p1dsnx_temp','us','p1dsnx_temp_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1dunkin_prospect','client_works','','p1dunkin','us','prospect_aws_db_p1dunkin_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1dunkin_prospect','client_works','','p1dunkin','us','p1dunkin_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1fca_prospect','client_works','','p1fca','us','prospect_aws_db_p1fca_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1fca_prospect','client_works','','p1fca','us','p1fca_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1gm_prospect','client_works','','p1gm','us','prospect_aws_db_p1gm_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1gm_prospect','client_works','','p1gm','us','p1gm_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1gnrl_prospect','client_works','','p1gnrl','us','prospect_aws_db_p1gnrl_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1gnrl_prospect','client_works','','p1gnrl','us','p1gnrl_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1infl_prospect','client_works','','p1infl','us','prospect_aws_db_p1infl_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1infl_prospect','client_works','','p1infl','us','p1infl_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1kellanova_prospect','client_works','','p1kellanova','us','prospect_aws_db_p1kellanova_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1kellanova_prospect','client_works','','p1kellanova','us','p1kellanova_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1kmb_prospect','client_works','','p1kmb','us','prospect_aws_db_p1kmb_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1kmb_prospect','client_works','','p1kmb','us','p1kmb_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1lowes_prospect','client_works','','p1lowes','us','prospect_aws_db_p1lowes_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1lowes_prospect','client_works','','p1lowes','us','p1lowes_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1macys_prospect','client_works','','p1macys','us','prospect_aws_db_p1macys_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1macys_prospect','client_works','','p1macys','us','p1macys_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1mars_prospect','client_works','','p1mars','us','prospect_aws_db_p1mars_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1mars_prospect','client_works','','p1mars','us','p1mars_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1mcdonalds_prospect','client_works','','p1mcdonalds','us','prospect_aws_db_p1mcdonalds_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1mcdonalds_prospect','client_works','','p1mcdonalds','us','p1mcdonalds_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1mfrm_prospect','client_works','','p1mfrm','us','prospect_aws_db_p1mfrm_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1mfrm_prospect','client_works','','p1mfrm','us','p1mfrm_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1panera_prospect','client_works','','p1panera','us','prospect_aws_db_p1panera_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1panera_prospect','client_works','','p1panera','us','p1panera_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1pcat_prospect','client_works','','p1pcat','us','prospect_aws_db_p1pcat_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1pcat_prospect','client_works','','p1pcat','us','p1pcat_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1pernod_prospect','client_works','','p1pernod','us','prospect_aws_db_p1pernod_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1pernod_prospect','client_works','','p1pernod','us','p1pernod_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1pfizer_prospect','client_works','','p1pfizer','us','prospect_aws_db_p1pfizer_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1pfizer_prospect','client_works','','p1pfizer','us','p1pfizer_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1planetfit_prospect','client_works','','p1planetfit','us','prospect_aws_db_p1planetfit_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1planetfit_prospect','client_works','','p1planetfit','us','p1planetfit_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1pmx_prospect','client_works','','p1pmx','us','prospect_aws_db_p1pmx_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1pmx_prospect','client_works','','p1pmx','us','p1pmx_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1ppal_prospect','client_works','','p1ppal','us','prospect_aws_db_p1ppal_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1ppal_prospect','client_works','','p1ppal','us','p1ppal_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1retargetly_prospect','client_works','','p1retargetly','us','prospect_aws_db_p1retargetly_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1retargetly_prospect','client_works','','p1retargetly','us','p1retargetly_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1rktm_prospect','client_works','','p1rktm','us','prospect_aws_db_p1rktm_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1rktm_prospect','client_works','','p1rktm','us','p1rktm_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1sbux_prospect','client_works','','p1sbux','us','prospect_aws_db_p1sbux_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1sbux_prospect','client_works','','p1sbux','us','p1sbux_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1signet_prospect','client_works','','p1signet','us','prospect_aws_db_p1signet_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1signet_prospect','client_works','','p1signet','us','p1signet_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1smsg_prospect','client_works','','p1smsg','us','prospect_aws_db_p1smsg_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1smsg_prospect','client_works','','p1smsg','us','p1smsg_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1spark_prospect','client_works','','p1spark','us','prospect_aws_db_p1spark_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1spark_prospect','client_works','','p1spark','us','p1spark_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1starcom_prospect','client_works','','p1starcom','us','prospect_aws_db_p1starcom_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1starcom_prospect','client_works','','p1starcom','us','p1starcom_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1tccc_prospect','client_works','','p1tccc','us','prospect_aws_db_p1tccc_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1tccc_prospect','client_works','','p1tccc','us','p1tccc_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1thrm_prospect','client_works','','p1thrm','us','prospect_aws_db_p1thrm_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1thrm_prospect','client_works','','p1thrm','us','p1thrm_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1tlmd_prospect','client_works','','p1tlmd','us','prospect_aws_db_p1tlmd_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1tlmd_prospect','client_works','','p1tlmd','us','p1tlmd_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1trpr_prospect','client_works','','p1trpr','us','prospect_aws_db_p1trpr_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1trpr_prospect','client_works','','p1trpr','us','p1trpr_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1ubs_prospect','client_works','','p1ubs','us','prospect_aws_db_p1ubs_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1ubs_prospect','client_works','','p1ubs','us','p1ubs_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1verizon_prospect','client_works','','p1verizon','us','prospect_aws_db_p1verizon_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1verizon_prospect','client_works','','p1verizon','us','p1verizon_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1wag_prospect','client_works','','p1wag','us','prospect_aws_db_p1wag_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1wag_prospect','client_works','','p1wag','us','p1wag_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1zenith_prospect','client_works','','p1zenith','us','prospect_aws_db_p1zenith_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p1zenith_prospect','client_works','','p1zenith','us','p1zenith_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p2atso_prospect','client_works','','p2atso','us','prospect_aws_db_p2atso_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('p2atso_prospect','client_works','','p2atso','us','p2atso_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('s1abcr_prospect','client_works','','s1abcr','us','prospect_aws_db_s1abcr_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('s1abcr_prospect','client_works','','s1abcr','us','s1abcr_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('s1epcr_prospect','client_works','','s1epcr','us','prospect_aws_db_s1epcr_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('s1epcr_prospect','client_works','','s1epcr','us','s1epcr_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('s1kccr_prospect','client_works','','s1kccr','us','prospect_aws_db_s1kccr_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('s1kccr_prospect','client_works','','s1kccr','us','s1kccr_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('s1pros_prospect','client_works','','s1pros','us','prospect_aws_db_s1pros_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('s1pros_prospect','client_works','','s1pros','us','s1pros_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('s1spnv_prospect','client_works','','s1spnv','us','prospect_aws_db_s1spnv_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('s1spnv_prospect','client_works','','s1spnv','us','s1spnv_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('t3pros_prospect','client_works','','t3pros','us','prospect_aws_db_t3pros_client','','','','yes','','','',current_date(),'davharsh@publicisgroupe.net',null,null),
('t3pros_prospect','client_works','','t3pros','us','t3pros_pcp_client_service_group','USE SCHEMA,SELECT','','','no','','','',current_date(),'davharsh@publicisgroupe.net',null,null);